@startuml

title Simple Factory

class Client
class SimpleFactory {
    + createProduct(): Product
}
interface Product
class ConcreteProduct

Client -> Product
Client --> SimpleFactory
ConcreteProduct .|> Product
SimpleFactory --> ConcreteProduct: "+creates"

@enduml